spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/iam_db
    username: iamuser
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

server:
  port: 8080